//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace RREntities
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class RrEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new RrEntities object using the connection string found in the 'RrEntities' section of the application configuration file.
        /// </summary>
        public RrEntities() : base("name=RrEntities", "RrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RrEntities object.
        /// </summary>
        public RrEntities(string connectionString) : base(connectionString, "RrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new RrEntities object.
        /// </summary>
        public RrEntities(EntityConnection connection) : base(connection, "RrEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<rr_history> rr_history
        {
            get
            {
                if ((_rr_history == null))
                {
                    _rr_history = base.CreateObjectSet<rr_history>("rr_history");
                }
                return _rr_history;
            }
        }
        private ObjectSet<rr_history> _rr_history;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the rr_history EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTorr_history(rr_history rr_history)
        {
            base.AddObject("rr_history", rr_history);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="rrModel", Name="rr_history")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class rr_history : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new rr_history object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="last_name">Initial value of the last_name property.</param>
        /// <param name="date">Initial value of the date property.</param>
        /// <param name="type">Initial value of the type property.</param>
        /// <param name="info">Initial value of the info property.</param>
        /// <param name="card_number">Initial value of the card_number property.</param>
        public static rr_history Createrr_history(global::System.Int64 id, global::System.String last_name, global::System.DateTime date, global::System.Int64 type, global::System.String info, global::System.Int64 card_number)
        {
            rr_history rr_history = new rr_history();
            rr_history.id = id;
            rr_history.last_name = last_name;
            rr_history.date = date;
            rr_history.type = type;
            rr_history.info = info;
            rr_history.card_number = card_number;
            return rr_history;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String first_name
        {
            get
            {
                return _first_name;
            }
            set
            {
                Onfirst_nameChanging(value);
                ReportPropertyChanging("first_name");
                _first_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("first_name");
                Onfirst_nameChanged();
            }
        }
        private global::System.String _first_name;
        partial void Onfirst_nameChanging(global::System.String value);
        partial void Onfirst_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String second_name
        {
            get
            {
                return _second_name;
            }
            set
            {
                Onsecond_nameChanging(value);
                ReportPropertyChanging("second_name");
                _second_name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("second_name");
                Onsecond_nameChanged();
            }
        }
        private global::System.String _second_name;
        partial void Onsecond_nameChanging(global::System.String value);
        partial void Onsecond_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String last_name
        {
            get
            {
                return _last_name;
            }
            set
            {
                Onlast_nameChanging(value);
                ReportPropertyChanging("last_name");
                _last_name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("last_name");
                Onlast_nameChanged();
            }
        }
        private global::System.String _last_name;
        partial void Onlast_nameChanging(global::System.String value);
        partial void Onlast_nameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime date
        {
            get
            {
                return _date;
            }
            set
            {
                OndateChanging(value);
                ReportPropertyChanging("date");
                _date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("date");
                OndateChanged();
            }
        }
        private global::System.DateTime _date;
        partial void OndateChanging(global::System.DateTime value);
        partial void OndateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 type
        {
            get
            {
                return _type;
            }
            set
            {
                OntypeChanging(value);
                ReportPropertyChanging("type");
                _type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("type");
                OntypeChanged();
            }
        }
        private global::System.Int64 _type;
        partial void OntypeChanging(global::System.Int64 value);
        partial void OntypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String info
        {
            get
            {
                return _info;
            }
            set
            {
                OninfoChanging(value);
                ReportPropertyChanging("info");
                _info = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("info");
                OninfoChanged();
            }
        }
        private global::System.String _info;
        partial void OninfoChanging(global::System.String value);
        partial void OninfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> birthday
        {
            get
            {
                return _birthday;
            }
            set
            {
                OnbirthdayChanging(value);
                ReportPropertyChanging("birthday");
                _birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birthday");
                OnbirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _birthday;
        partial void OnbirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnbirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 card_number
        {
            get
            {
                return _card_number;
            }
            set
            {
                Oncard_numberChanging(value);
                ReportPropertyChanging("card_number");
                _card_number = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("card_number");
                Oncard_numberChanged();
            }
        }
        private global::System.Int64 _card_number;
        partial void Oncard_numberChanging(global::System.Int64 value);
        partial void Oncard_numberChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] photo
        {
            get
            {
                return StructuralObject.GetValidValue(_photo);
            }
            set
            {
                OnphotoChanging(value);
                ReportPropertyChanging("photo");
                _photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("photo");
                OnphotoChanged();
            }
        }
        private global::System.Byte[] _photo;
        partial void OnphotoChanging(global::System.Byte[] value);
        partial void OnphotoChanged();

        #endregion
    
    }

    #endregion
    
}
